
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class ManageDetails extends javax.swing.JFrame {

    /**
     * Creates new form ManageDetails
     */
    public ManageDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameNV = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        manv = new javax.swing.JTextField();
        tennv = new javax.swing.JTextField();
        ngaysinh = new javax.swing.JTextField();
        diachi = new javax.swing.JTextField();
        sdt = new javax.swing.JTextField();
        gioitinh = new javax.swing.JTextField();
        xemnv = new javax.swing.JButton();
        themnv = new javax.swing.JButton();
        xoanv = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jOptionPane1 = new javax.swing.JOptionPane();
        frameSP = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        masp = new javax.swing.JTextField();
        tensp = new javax.swing.JTextField();
        donvi = new javax.swing.JTextField();
        gia = new javax.swing.JTextField();
        xemsp = new javax.swing.JButton();
        suasp = new javax.swing.JButton();
        xoasp = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        frameHD = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        mahdd = new javax.swing.JTextField();
        manvhd = new javax.swing.JTextField();
        ngaygiao = new javax.swing.JTextField();
        type = new javax.swing.JTextField();
        ngaylap = new javax.swing.JTextField();
        description = new javax.swing.JTextField();
        themhd = new javax.swing.JButton();
        suahd = new javax.swing.JButton();
        xoahd = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        nextstep = new javax.swing.JButton();
        detail = new javax.swing.JFrame();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        maspdt = new javax.swing.JTextField();
        sl = new javax.swing.JTextField();
        mahdlb = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        frameNV.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                frameNVWindowOpened(evt);
            }
        });

        jLabel2.setText("Ma Nhan Vien");

        jLabel3.setText("Ten Nhan Vien");

        jLabel4.setText("Ngay Sinh");

        jLabel5.setText("Dia Chi");

        jLabel6.setText("So Dien Thoai");

        jLabel7.setText("Gioi Tinh");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Ma Nhan Vien", "Ten Nhan Vien", "Ngay Sinh", "Dia Chi", "So Dien Thoai", "Gioi Tinh"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        sdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdtActionPerformed(evt);
            }
        });

        gioitinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gioitinhActionPerformed(evt);
            }
        });

        xemnv.setText("Search");
        xemnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xemnvActionPerformed(evt);
            }
        });

        themnv.setText("New...");
        themnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themnvActionPerformed(evt);
            }
        });

        xoanv.setText("Remove");
        xoanv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoanvActionPerformed(evt);
            }
        });

        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel8.setText("format: dd/mm/yyyy");

        jButton8.setText("Refresh");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameNVLayout = new javax.swing.GroupLayout(frameNV.getContentPane());
        frameNV.getContentPane().setLayout(frameNVLayout);
        frameNVLayout.setHorizontalGroup(
            frameNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameNVLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(frameNVLayout.createSequentialGroup()
                        .addGroup(frameNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(frameNVLayout.createSequentialGroup()
                                .addGroup(frameNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(50, 50, 50)
                                .addGroup(frameNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(manv, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(frameNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tennv, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                        .addComponent(ngaysinh)
                                        .addComponent(diachi))))
                            .addGroup(frameNVLayout.createSequentialGroup()
                                .addGroup(frameNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(54, 54, 54)
                                .addGroup(frameNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sdt)
                                    .addComponent(gioitinh))))
                        .addGroup(frameNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameNVLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(frameNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameNVLayout.createSequentialGroup()
                                        .addGroup(frameNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(themnv)
                                            .addComponent(xemnv)
                                            .addComponent(xoanv))
                                        .addGap(58, 58, 58))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameNVLayout.createSequentialGroup()
                                        .addComponent(jButton7)
                                        .addGap(69, 69, 69))))
                            .addGroup(frameNVLayout.createSequentialGroup()
                                .addGroup(frameNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton8)
                                    .addComponent(jLabel8))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        frameNVLayout.setVerticalGroup(
            frameNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameNVLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(frameNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(manv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xemnv))
                .addGroup(frameNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameNVLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(frameNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tennv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(frameNVLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(themnv)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(frameNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameNVLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(frameNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(frameNVLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(xoanv)))
                .addGap(18, 18, 18)
                .addGroup(frameNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addGroup(frameNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
        );

        frameSP.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                frameSPWindowOpened(evt);
            }
        });

        jLabel9.setText("Ma San Pham");

        jLabel10.setText("Ten San Pham");

        jLabel11.setText("Don Vi");

        jLabel12.setText("Gia");

        xemsp.setText("Xem");
        xemsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xemspActionPerformed(evt);
            }
        });

        suasp.setText("Sua");
        suasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaspActionPerformed(evt);
            }
        });

        xoasp.setText("Xoa");
        xoasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaspActionPerformed(evt);
            }
        });

        jButton12.setText("Back");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ma San Pham", "Ten San Pham", "Don Vi", "Gia"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout frameSPLayout = new javax.swing.GroupLayout(frameSP.getContentPane());
        frameSP.getContentPane().setLayout(frameSPLayout);
        frameSPLayout.setHorizontalGroup(
            frameSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameSPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameSPLayout.createSequentialGroup()
                        .addGroup(frameSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(frameSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(gia)
                            .addComponent(donvi)
                            .addComponent(tensp)
                            .addComponent(masp, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGroup(frameSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(frameSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(frameSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(frameSPLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(xemsp))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameSPLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(suasp)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameSPLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(xoasp)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameSPLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton12))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameSPLayout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        frameSPLayout.setVerticalGroup(
            frameSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameSPLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(frameSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(masp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xemsp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frameSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suasp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frameSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(donvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xoasp))
                .addGap(18, 18, 18)
                .addGroup(frameSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        frameHD.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                frameHDWindowOpened(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Ma Hoa Don", "Ma Nhan Vien", "Loai Hoa Don", "Ngay Lap", "Ngay Giao", "Chu Thich"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel13.setText("Ma Hoa Don");

        jLabel14.setText("Ma Nhan Vien");

        jLabel15.setText("Loai Hoa Don");

        jLabel16.setText("Ngay Lap");

        jLabel17.setText("Ngay Kiem Hang");

        jLabel18.setText("Chu Thich");

        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });

        themhd.setText("Them");
        themhd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themhdActionPerformed(evt);
            }
        });

        suahd.setText("Sua");
        suahd.setToolTipText("");
        suahd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suahdActionPerformed(evt);
            }
        });

        xoahd.setText("Xoa");
        xoahd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoahdActionPerformed(evt);
            }
        });

        jButton9.setText("Back");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        nextstep.setText("Chi Tiet");
        nextstep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextstepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameHDLayout = new javax.swing.GroupLayout(frameHD.getContentPane());
        frameHD.getContentPane().setLayout(frameHDLayout);
        frameHDLayout.setHorizontalGroup(
            frameHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameHDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(frameHDLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(frameHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(frameHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13)
                        .addGroup(frameHDLayout.createSequentialGroup()
                            .addGroup(frameHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16)
                                .addComponent(jLabel18))
                            .addGap(18, 18, 18)
                            .addGroup(frameHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ngaylap)
                                .addComponent(type)
                                .addComponent(description)
                                .addComponent(mahdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(frameHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nextstep)
                        .addGroup(frameHDLayout.createSequentialGroup()
                            .addComponent(themhd)
                            .addGap(73, 73, 73)
                            .addComponent(suahd))))
                .addGroup(frameHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameHDLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                        .addGroup(frameHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(frameHDLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(manvhd, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(frameHDLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(frameHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton9)
                                    .addComponent(ngaygiao))))
                        .addGap(234, 234, 234))
                    .addGroup(frameHDLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(xoahd)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        frameHDLayout.setVerticalGroup(
            frameHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameHDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(mahdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manvhd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(frameHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(frameHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(ngaygiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ngaylap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(frameHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(frameHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themhd)
                    .addComponent(suahd)
                    .addComponent(xoahd)
                    .addComponent(jButton9))
                .addGap(11, 11, 11)
                .addComponent(nextstep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        detail.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                detailWindowOpened(evt);
            }
        });

        jLabel19.setText("Ma Hoa Don");

        jLabel20.setText("Ma San Pham");

        jLabel21.setText("So Luong");

        mahdlb.setText("<>");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ma Hoa Don", "Ten San Pham", "So Luong", "Thanh Tien"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jButton4.setText("Them");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout detailLayout = new javax.swing.GroupLayout(detail.getContentPane());
        detail.getContentPane().setLayout(detailLayout);
        detailLayout.setHorizontalGroup(
            detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
            .addGroup(detailLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(detailLayout.createSequentialGroup()
                        .addComponent(mahdlb)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(detailLayout.createSequentialGroup()
                        .addGroup(detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailLayout.createSequentialGroup()
                                .addComponent(maspdt, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailLayout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(101, 101, 101)))
                        .addGroup(detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addComponent(sl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(121, 121, 121))))
        );
        detailLayout.setVerticalGroup(
            detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(mahdlb))
                .addGap(51, 51, 51)
                .addGroup(detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(maspdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Administrator");

        jButton1.setText("Nhan Vien");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("San Pham");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hoa Don");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addGap(51, 51, 51)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sdtActionPerformed

    private void gioitinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gioitinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gioitinhActionPerformed

    private void frameNVWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_frameNVWindowOpened
    Connection con=null;
       
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@//192.168.1.111:1521/PDB1","anhnx","3872335");
            if(con!=null){
                Statement state=con.createStatement();
                ResultSet rs=state.executeQuery("select manv,tennv,ngaysinh,diachi,sdt,gioitinh from anhnx.nhanvien");
                int i=0;
                while(rs.next()){
                    jTable1.getModel().setValueAt(rs.getString("manv"),i,0);
                    jTable1.getModel().setValueAt(rs.getString("tennv"), i, 1);
                    jTable1.getModel().setValueAt(rs.getString("ngaysinh"),i,2);
                    jTable1.getModel().setValueAt(rs.getString("diachi"),i,3);
                    jTable1.getModel().setValueAt(rs.getString("sdt"),i,4);
                    jTable1.getModel().setValueAt(rs.getString("gioitinh"),i,5);
                    i++;
                }
            }
        }catch (ClassNotFoundException | SQLException ex){
            Logger.getLogger(ManageDetails.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_frameNVWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    frameNV.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frameNV.pack();
        frameNV.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void themnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themnvActionPerformed
            Connection con=null;
        String f1,f2,f3,f4,f5,f6;
        f1=this.manv.getText();
        f2=this.tennv.getText();
        f3=this.ngaysinh.getText();
        f4=this.diachi.getText();
        f5=this.sdt.getText();
        f6=this.gioitinh.getText();
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@//192.168.1.111:1521/PDB1","anhnx","3872335");
            Statement stmt=con.createStatement();

        if(con!=null) {
            System.out.println("Success!");
        }
        else {
            System.out.println("Failed!");
        }

        String sql = "Insert into anhnx.nhanvien values('"+f1+"','"+f2+"',to_date('"+f3+"','dd/mm/yyyy'),'"+f4+"','"+f5+"','"+f6+"')";
        Statement st=con.createStatement();
        int n=st.executeUpdate(sql);
        //System.out.println(n+" "+"record inserted");

        if (n==1) {
            jOptionPane1.showMessageDialog(this,"Record inserted");
        }
        else {
            jOptionPane1.showMessageDialog(this,"Record not inserted");
        }

        con.close();

    } catch(Exception e) {System.out.println(e);
        }
    }//GEN-LAST:event_themnvActionPerformed

    private void xoanvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoanvActionPerformed
        Connection con=null;
        String f1,f2;
        f1=this.manv.getText();
        f2=this.tennv.getText();
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@//192.168.1.111:1521/PDB1","anhnx","3872335");
            Statement stmt=con.createStatement();

        if(con!=null) {
            System.out.println("Success!");
        }
        else {
            System.out.println("Failed!");
        }

        String sql = "delete from anhnx.nhanvien where manv='"+f1+"' or tennv='"+f2+"'";
        Statement st=con.createStatement();
        int n=st.executeUpdate(sql);
        //System.out.println(n+" "+"record inserted");

        if (n==1) {
            jOptionPane1.showMessageDialog(this,"Record removed");
        }
        else {
            jOptionPane1.showMessageDialog(this,"Remove incomplete");
        }

        con.close();

    } catch(Exception e) {System.out.println(e);
        }
    }//GEN-LAST:event_xoanvActionPerformed

    private void xemnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xemnvActionPerformed
     
        Connection con=null;
        String f1,f2;
        f1=this.manv.getText();
        f2=this.tennv.getText();
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@//192.168.1.111:1521/PDB1","anhnx","3872335");
            if(con!=null){
                Statement state=con.createStatement();
                ResultSet rs=state.executeQuery("select manv, tennv, to_char(ngaysinh,'dd/mm/yyyy') ngaysinh, diachi, sdt, gioitinh from anhnx.nhanvien where 1=1 and manv='"+f1+"'");
                int i=0;
                while(rs.next()){
                    this.manv.setText(rs.getString("manv")+"");
                    this.tennv.setText(rs.getString("tennv"));
                    this.ngaysinh.setText(rs.getString("ngaysinh"));
                    this.diachi.setText(rs.getString("diachi"));
                    this.sdt.setText(rs.getString("sdt"));
                    this.gioitinh.setText(rs.getString("gioitinh"));
                }
            }
            con.close();       
        }catch (ClassNotFoundException | SQLException ex){
            Logger.getLogger(ManageDetails.class.getName()).log(Level.SEVERE,null,ex);
        }
       
    }//GEN-LAST:event_xemnvActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.manv.setText(null);
        this.tennv.setText(null);
        this.ngaysinh.setText(null);
        this.diachi.setText(null);
        this.sdt.setText(null);
        this.gioitinh.setText(null);
        Connection con=null;
       
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@//192.168.1.111:1521/PDB1","anhnx","3872335");
            if(con!=null){
                Statement state=con.createStatement();
                ResultSet rs=state.executeQuery("select manv,tennv,ngaysinh,diachi,sdt,gioitinh from anhnx.nhanvien");
                int i=0;
                while(rs.next()){
                    jTable1.getModel().setValueAt(rs.getString("manv"),i,0);
                    jTable1.getModel().setValueAt(rs.getString("tennv"), i, 1);
                    jTable1.getModel().setValueAt(rs.getString("ngaysinh"),i,2);
                    jTable1.getModel().setValueAt(rs.getString("diachi"),i,3);
                    jTable1.getModel().setValueAt(rs.getString("sdt"),i,4);
                    jTable1.getModel().setValueAt(rs.getString("gioitinh"),i,5);
                    i++;
                }
            }
        }catch (ClassNotFoundException | SQLException ex){
            Logger.getLogger(ManageDetails.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         this.manv.setText(null);
        this.tennv.setText(null);
        this.ngaysinh.setText(null);
        this.diachi.setText(null);
        this.sdt.setText(null);
        this.gioitinh.setText(null);      
        frameNV.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void xemspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xemspActionPerformed
        Connection con=null;
        String f1,f2;
        f1=this.masp.getText();
        f2=this.tensp.getText();
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@//192.168.1.111:1521/PDB1","anhnx","3872335");
            if(con!=null){
                Statement state=con.createStatement();
                ResultSet rs=state.executeQuery("select* from anhnx.sanphamm where 1=1 and masp='"+f1+"'");
                int i=0;
                while(rs.next()){
                    this.masp.setText(rs.getString("masp")+"");
                    this.tensp.setText(rs.getString("tensp"));
                    this.donvi.setText(rs.getString("donvi"));
                    this.gia.setText(rs.getString("gia"));
                }
            }
        }catch (ClassNotFoundException | SQLException ex){
            Logger.getLogger(ManageDetails.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_xemspActionPerformed

    private void frameSPWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_frameSPWindowOpened
            Connection con=null;
       
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@//192.168.1.111:1521/PDB1","anhnx","3872335");
            if(con!=null){
                Statement state=con.createStatement();
                ResultSet rs=state.executeQuery("select masp, tensp, donvi, gia from anhnx.sanphamm");
                int i=0;
                while(rs.next()){
                    jTable2.getModel().setValueAt(rs.getString("masp"),i,0);
                    jTable2.getModel().setValueAt(rs.getString("tensp"), i,1);
                    jTable2.getModel().setValueAt(rs.getString("donvi"),i,2);
                    jTable2.getModel().setValueAt(rs.getString("gia"),i,3);
                    i++;
                }
            }
        }catch (ClassNotFoundException | SQLException ex){
            Logger.getLogger(ManageDetails.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_frameSPWindowOpened

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        this.masp.setText(null);
        this.tensp.setText(null);
        this.donvi.setText(null);
        this.gia.setText(null);
        frameSP.setVisible(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        frameSP.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frameSP.pack();
        frameSP.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void suaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaspActionPerformed
        Connection con=null;
        String f1,f2,f3,f4;
        f1=this.masp.getText();
        f2=this.tensp.getText();
        f3=this.donvi.getText();
        f4=this.gia.getText();
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@//192.168.1.111:1521/PDB1","anhnx","3872335");
            Statement stmt=con.createStatement();
        String sql = "update anhnx.sanphamm  set tensp='"+f2+"', donvi='"+f3+"', gia='"+f4+"' where masp='"+f1+"'";
        Statement st=con.createStatement();
        int n=st.executeUpdate(sql);
        //System.out.println(n+" "+"record inserted");

        if (n==1) {
            jOptionPane1.showMessageDialog(this,"Updated");
        }
        else {
            jOptionPane1.showMessageDialog(this,"Update error");
        }

        con.close();

    } catch(Exception e) {System.out.println(e);
        }
    }//GEN-LAST:event_suaspActionPerformed

    private void xoaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaspActionPerformed
        Connection con=null;
        String f1;
        f1=this.masp.getText();
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@//192.168.1.111:1521/PDB1","anhnx","3872335");
            Statement stmt=con.createStatement();
        String sql = "delete from anhnx.sanphamm where masp='"+f1+"'";
        Statement st=con.createStatement();
        int n=st.executeUpdate(sql);
        //System.out.println(n+" "+"record inserted");

        if (n==1) {
            jOptionPane1.showMessageDialog(this,"Removed");
        }
        else {
            jOptionPane1.showMessageDialog(this,"Remove failed");
        }

        con.close();

    } catch(Exception e) {System.out.println(e);
        }
    }//GEN-LAST:event_xoaspActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        this.mahdd.setText(null);
        this.manvhd.setText(null);
        this.ngaylap.setText(null);
        this.ngaygiao.setText(null);
        this.type.setText(null);
        this.description.setText(null);
        frameHD.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void themhdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themhdActionPerformed
        
        Connection con=null;
        String f1,f2,f3,f4,f5,f6;
        f1=this.mahdd.getText();
        f2=this.manvhd.getText();
        f3=this.type.getText();
        f4=this.ngaylap.getText();
        f5=this.ngaygiao.getText();
        f6=this.description.getText();
        
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@//192.168.1.111:1521/PDB1","anhnx","3872335");
            Statement stmt=con.createStatement();

        if(con!=null) {
            System.out.println("Success!");
        }
        else {
            System.out.println("Failed!");
        }

        String sql = "Insert into anhnx.hoadon values('"+f1+"','"+f2+"','"+f3+"',to_date('"+f4+"','dd/mm/yyyy'),to_date('"+f5+"','dd/mm/yyyy'),'"+f6+"')";
        Statement st=con.createStatement();
        int n=st.executeUpdate(sql);
        //System.out.println(n+" "+"record inserted");
        if (n==1) {
            jOptionPane1.showMessageDialog(this,"Inserted");
        }
        else {
            jOptionPane1.showMessageDialog(this,"Insert failed");
        }
        
        con.close();

    } catch(Exception e) {System.out.println(e);
        }
    }//GEN-LAST:event_themhdActionPerformed

    private void frameHDWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_frameHDWindowOpened
        Connection con=null;
       
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@//192.168.1.111:1521/PDB1","anhnx","3872335");
            if(con!=null){
                Statement state=con.createStatement();
                ResultSet rs=state.executeQuery("select mahd, manv, type, ngaylap, ngaygiao, description from anhnx.hoadon");
                int i=0;
                while(rs.next()){
                    jTable3.getModel().setValueAt(rs.getString("mahd"),i,0);
                    jTable3.getModel().setValueAt(rs.getString("manv"), i,1);
                    jTable3.getModel().setValueAt(rs.getString("type"),i,2);
                    jTable3.getModel().setValueAt(rs.getString("ngaylap"),i,3);
                    jTable3.getModel().setValueAt(rs.getString("ngaygiao"),i,4);
                    jTable3.getModel().setValueAt(rs.getString("description"),i,5);
                    i++;
                }
            }
        }catch (ClassNotFoundException | SQLException ex){
            Logger.getLogger(ManageDetails.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_frameHDWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    frameHD.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frameHD.pack();
        frameHD.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void detailWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_detailWindowOpened
        
        Connection con=null;
        String vl=mahdd.getText();
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@//192.168.1.111:1521/PDB1","anhnx","3872335");
            if(con!=null){
                Statement state=con.createStatement();
                ResultSet rs=state.executeQuery("select dt.mahd, sp.tensp tensp, dt.soluong soluong, TO_CHAR((dt.soluong*sp.gia),'99999999','NLS_NUMERIC_CHARACTERS = ''.''''''NLS_CURRENCY = ''$'' ') thanhtien from chitiethoadon dt, sanphamm sp where 1=1 and dt.masp=sp.masp and mahd='"+vl+"'");
                int i=0;
                while(rs.next()){
                    jTable4.getModel().setValueAt(rs.getString("mahd"),i,0);
                    jTable4.getModel().setValueAt(rs.getString("tensp"), i,1);
                    jTable4.getModel().setValueAt(rs.getString("soluong"),i,2);
                    jTable4.getModel().setValueAt(rs.getString("thanhtien"),i,3);
                    i++;
                }
            }
        }catch (ClassNotFoundException | SQLException ex){
            Logger.getLogger(ManageDetails.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_detailWindowOpened

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String f1,f2,f3;
        f1=this.mahdlb.getText();
        f2=this.maspdt.getText();
        f3=this.sl.getText();
        Connection con=null;
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@//192.168.1.111:1521/PDB1","anhnx","3872335");
            Statement stmt=con.createStatement();

        if(con!=null) {
            System.out.println("Success!");
        }
        else {
            System.out.println("Failed!");
        }

        String sql = "Insert into anhnx.chitiethoadon values('"+f1+"','"+f2+"','"+f3+"')";
        Statement st=con.createStatement();
        int n=st.executeUpdate(sql);
        //System.out.println(n+" "+"record inserted");

        if (n==1) {
            jOptionPane1.showMessageDialog(this,"Record inserted");
        }
        else {
            jOptionPane1.showMessageDialog(this,"Record not inserted");
        }       
        con.close();

    } catch(Exception e) {System.out.println(e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void nextstepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextstepActionPerformed
        String f1=mahdd.getText();
        this.mahdlb.setText(f1);
        frameHD.setVisible(false);
        detail.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        detail.pack();
        detail.setVisible(true);
    }//GEN-LAST:event_nextstepActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.mahdlb.setText(null);
        this.maspdt.setText(null);
        this.sl.setText(null);
       
        detail.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void suahdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suahdActionPerformed
        Connection con=null;
        String f1,f2,f3,f4,f5,f6;
        f1=this.mahdd.getText();
        f2=this.manvhd.getText();
        f3=this.type.getText();
        f4=this.ngaylap.getText();
        f5=this.ngaygiao.getText();
        f6=this.description.getText();
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@//192.168.1.111:1521/PDB1","anhnx","3872335");
            Statement stmt=con.createStatement();
        String sql = "update anhnx.hoadon  set manv='"+f2+"', type='"+f3+"', ngaylap=to_date('"+f4+"','dd/mm/yyyy'), ngaygiao=to_date('"+f5+"','dd/mm/yyyy'), description='"+f6+"' where mahd='"+f1+"'";
        Statement st=con.createStatement();
        int n=st.executeUpdate(sql);
        //System.out.println(n+" "+"record inserted");

        if (n==1) {
            jOptionPane1.showMessageDialog(this,"Updated");
        }
        else {
            jOptionPane1.showMessageDialog(this,"Update error");
        }

        con.close();

    } catch(Exception e) {System.out.println(e);
        }
    }//GEN-LAST:event_suahdActionPerformed

    private void xoahdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoahdActionPerformed
        Connection con=null;
        String f1;
        f1=this.mahdd.getText();
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@//192.168.1.111:1521/PDB1","anhnx","3872335");
            Statement stmt=con.createStatement();
        String sql = "delete from anhnx.hoadon where mahd='"+f1+"'";
        Statement st=con.createStatement();
        int n=st.executeUpdate(sql);
        //System.out.println(n+" "+"record inserted");

        if (n==1) {
            jOptionPane1.showMessageDialog(this,"Removed");
        }
        else {
            jOptionPane1.showMessageDialog(this,"Remove failed");
        }

        con.close();

    } catch(Exception e) {System.out.println(e);
        }
    }//GEN-LAST:event_xoahdActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField description;
    private javax.swing.JFrame detail;
    private javax.swing.JTextField diachi;
    private javax.swing.JTextField donvi;
    private javax.swing.JFrame frameHD;
    private javax.swing.JFrame frameNV;
    private javax.swing.JFrame frameSP;
    private javax.swing.JTextField gia;
    private javax.swing.JTextField gioitinh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    public static javax.swing.JTextField mahdd;
    private javax.swing.JLabel mahdlb;
    private javax.swing.JTextField manv;
    private javax.swing.JTextField manvhd;
    private javax.swing.JTextField masp;
    private javax.swing.JTextField maspdt;
    private javax.swing.JButton nextstep;
    private javax.swing.JTextField ngaygiao;
    private javax.swing.JTextField ngaylap;
    private javax.swing.JTextField ngaysinh;
    private javax.swing.JTextField sdt;
    private javax.swing.JTextField sl;
    private javax.swing.JButton suahd;
    private javax.swing.JButton suasp;
    private javax.swing.JTextField tennv;
    private javax.swing.JTextField tensp;
    private javax.swing.JButton themhd;
    private javax.swing.JButton themnv;
    private javax.swing.JTextField type;
    private javax.swing.JButton xemnv;
    private javax.swing.JButton xemsp;
    private javax.swing.JButton xoahd;
    private javax.swing.JButton xoanv;
    private javax.swing.JButton xoasp;
    // End of variables declaration//GEN-END:variables
}
